name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "npm"
      - run: npm ci
      - run: npm test

  create:
    name: Create
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        node-version: [18.x, 20.x, 22.x]
        package-manager: [npm, yarn, pnpm]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        if: matrix.package-manager == 'pnpm'
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm install --production
      - run: npm install --global .

      - name: Create empty package.json for pnpm
        run: |
          with open("package.json", "w") as f:
            f.write('{}')
        shell: python
        working-directory: ${{ runner.temp }}
        if: matrix.package-manager == 'pnpm'
      - run: ${{ matrix.package-manager }} exec create-ts-node new-project
        working-directory: ${{ runner.temp }}
      - run: ${{ matrix.package-manager }} install
        working-directory: ${{ runner.temp }}/new-project
      - run: ${{ matrix.package-manager }} run build
        working-directory: ${{ runner.temp }}/new-project
      - run: ${{ matrix.package-manager }} test
        working-directory: ${{ runner.temp }}/new-project
